version: "3.8"

services:

  backend:
    image: rhilwerda/gentrend-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/fastapi-app

  ##TODO: Add volume for backend files ./database:/app/backend

  frontend:
    image: rhilwerda/gentrend-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src



